### ISSUE TITLE
Scripts not installed as executables

### ISSUE THREAD

**Issue by dmopalmer** [conda-forge/pyxb-feedstock#2]
When installing pyxb, the corresponding scripts ( pyxbdump, pyxbgen, pyxbwsdl ) are installed in the envs/*/bin directory, but are not marked as executable.
```
(test) % conda install -c conda-forge pyxb
...
(test) % ls -l bin/pyxb*
-rw-rw-r--  1 palmer  staff  1540 Jan 11 17:33 bin/pyxbdump
-rw-rw-r--  1 palmer  staff  2694 Jan 11 17:33 bin/pyxbgen
-rw-rw-r--  1 palmer  staff  1916 Jan 11 17:33 bin/pyxbwsdl
```

This is under both linux and macOSX.

**Comment by grlee77** [comment]
I can reproduce this, but I'm not sure why this should be.  If I build the recipe locally and then install using `conda install --use-local pyxb` they do end up as executable.

**Comment by grlee77** [comment]
actually, looking at it again, I also end up with the files as non-executable when building the recipe locally.  Interestingly the corresponding scripts within the file `~/anaconda/conda-bld/noarch/pyxb-1.2.6-py_0.tar.bz2` are executable, but somehow this is no longer the case after installation.

**Comment by microe** [comment]
The package currently on conda-forge does not have executable bits:
```
$tar tvf ~/Downloads/pyxb-1.2.6-py_0.tar.bz2 | grep pyxbgen
-rw-rw-r-- root/root      2694 2017-09-10 07:12 python-scripts/pyxbgen
```

I have seen this in my own custom noarch packages when not using pip to build the package.
